// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLocalePicker: typeof import('./src/components/common/appLocalePicker.vue')['default']
    Confirm: typeof import('./src/components/common/confirmbox/confirm.vue')['default']
    FormTest: typeof import('./src/components/form-test.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/common/svg-icon.vue')['default']
    UsePinia: typeof import('./src/components/UsePinia.vue')['default']
  }
}
